<html>
<head>
    <title>Criar Conta</title>
    <meta name="layout" content="external">
</head>
<body page-title="Criar Conta">
    <atlas-panel>
        <atlas-form method="post" action="${createLink(controller: "customer", action: "save")}">
            <atlas-grid>
                <atlas-row>
                    <atlas-col>
                        <atlas-input
                            label="Nome"
                            name="name"
                            required="true"
                            value="${customer?.name}"
                        >
                        </atlas-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-masked-input
                            label="Email"
                            name="email"
                            mask-alias="email"
                            required="true"
                            value="${customer?.email}"
                        >
                        </atlas-masked-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-masked-input
                            label="CPF/CNPJ"
                            name="cpfCnpj"
                            mask-alias="cpf-cnpj"
                            required="true"
                            value="${customer?.cpfCnpj}"
                        >
                        </atlas-masked-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-postal-code
                            label="CEP"
                            name="address.cep"
                            required="true"
                            value="${customer?.address?.cep}"
                        >
                        </atlas-postal-code>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-input
                            label="Cidade"
                            name="address.city"
                            required="true"
                            value="${customer?.address?.city}"
                        >
                        </atlas-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-input
                            label="Estado"
                            name="address.state"
                            required="true"
                            value="${customer?.address?.state}"
                        >
                        </atlas-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-input
                            label="Complemento"
                            name="address.complement"
                            required="false"
                            value="${customer?.address?.complement}"
                        >
                        </atlas-input>
                    </atlas-col>
                </atlas-row>


               <atlas-row>
                    <atlas-col>
                        <atlas-masked-input
                            label="Usuário"
                            name="adminEmail"
                            mask-alias="email"
                            required="true"
                            value="${customer?.adminEmail}"
                        >
                        </atlas-masked-input>
                    </atlas-col>
                </atlas-row>
                <atlas-row>
                    <atlas-col>
                        <atlas-password-input
                            label="Senha"
                            name="adminPassword"
                            required="true"
                            value="${customer?.adminPassword}"
                            remove-visibility-icon>
                        >
                        </atlas-password-input>
                    </atlas-col>
                </atlas-row>
            </atlas-grid>
            <atlas-button submit description="Salvar"></atlas-button>
        </atlas-form>
    </atlas-panel>
</body>
</html>
